### ISSUE TITLE
.png格式图片转换失败

### ISSUE THREAD

**Issue by meowstatery** [CWEIB/Holo-Bin_Tool#1]
如题。
选用的文件是文件夹里提供的天气图片文件，拖拽之后的结果如下图所示。
![bug](https://user-images.githubusercontent.com/79510201/111076791-cbd74180-8528-11eb-9e27-1d96b35a9980.png)

**Comment by Code-30** [comment]
补充：如上图可见，本图片路径无空格

**Comment by meowstatery** [comment]
已知晓错误原因：原始图片路径不能存在空格

**Comment by CWEIB** [comment]
问题已修复，请下载最新的软件
